### ISSUE TITLE
同一路径程序运行多个进程时，workid会重复

### ISSUE THREAD

**Issue by MayGodBlessYouAMen** [LemonNoCry/SnowflakeId.AutoRegister#1]
示例中通过程序路径做的区分：
SetExtraIdentifier(Environment.CurrentDirectory);
看到类库中也加上了机器Mac地址：
 Identifier = Md5Util.ComputeMd5(MacUtil.GetMacAddress() + registerOption.ExtraIdentifier);

但是我测试示例[Yitter.IdGenerator.Fx.AutoRegister]时，通过ctrl+f5同时启动了多个进程，显示的WorkId都是1。
有没有办法能解决这个问题?

之所以问这个问题。因为我实际生产环境中使用IIS最大工作进程设置成了10，导致WorkId重复，现在正在尝试通过这个库解决问题。

期待你的回复，感谢。

![2024-11-29_10-13-26](https://github.com/user-attachments/assets/7e45685b-af7d-463a-9d8e-8ba3c3767e36)

**Comment by LemonNoCry** [comment]
获取到同一个WorkId的原因:
同一个进程运行多次，自然这些唯一标识都是一样的,因为会优先获取之前的WorkId

按你的描述:
IIS多进程都是同一个exe,你之前是在web.config中配置WorkId导致重复?

**Comment by LemonNoCry** [comment]
如果有这个多进程场景，可以尝试标识符添加进程pid来解决

``` C#
int currentProcessId = Process.GetCurrentProcess().Id;
SetExtraIdentifier(Environment.CurrentDirectory+currentProcessId.ToString());
```

**Comment by MayGodBlessYouAMen** [comment]
> 获取到同一个WorkId的原因: 同一个进程运行多次，自然这些唯一标识都是一样的,因为会优先获取之前的WorkId
> 
> 按你的描述: IIS多进程都是同一个exe,你之前是在web.config中配置WorkId导致重复?

之前确实是在web.config中配置的WorkId，所以多个进程读取出来就是同一个。

**Comment by MayGodBlessYouAMen** [comment]
> 如果有这个多进程场景，可以尝试标识符添加进程pid来解决
> 
> ```cs
> int currentProcessId = Process.GetCurrentProcess().Id;
> SetExtraIdentifier(Environment.CurrentDirectory+currentProcessId.ToString());
> ```

好的，我先试试

**Comment by MayGodBlessYouAMen** [comment]
> 如果有这个多进程场景，可以尝试标识符添加进程pid来解决
> 
> ```cs
> int currentProcessId = Process.GetCurrentProcess().Id;
> SetExtraIdentifier(Environment.CurrentDirectory+currentProcessId.ToString());
> ```

另外我问一下。
如果程序意外挂了，导致注销代码AutoRegister.UnRegister()没有运行，那当前这个WorkId是不是就以后再也获取不到了？
长时间后，程序意外挂掉次数累积多了，会不会有WorkId耗尽的风险？

**Comment by LemonNoCry** [comment]
> > 如果有这个多进程场景，可以尝试标识符添加进程pid来解决
> > ```cs
> > int currentProcessId = Process.GetCurrentProcess().Id;
> > SetExtraIdentifier(Environment.CurrentDirectory+currentProcessId.ToString());
> > ```
> 
> 另外我问一下。 如果程序意外挂了，导致注销代码AutoRegister.UnRegister()没有运行，那当前这个WorkId是不是就以后再也获取不到了？ 长时间后，程序意外挂掉次数累积多了，会不会有WorkId耗尽的风险？

1.程序挂了，再启动会尝试获取上一次的workid，但因为你没有唯一标识所以获取不到，基本上可以理解每次都是新的
2.不会，默认WorkId生命周期是30秒,可以手动调整,只有程序没挂会不断续期

``` c#
.SetRegisterOption(option => option.WorkerIdLifeMillisecond = 100)
```

**Comment by MayGodBlessYouAMen** [comment]
> > > 如果有这个多进程场景，可以尝试标识符添加进程pid来解决
> > > ```cs
> > > int currentProcessId = Process.GetCurrentProcess().Id;
> > > SetExtraIdentifier(Environment.CurrentDirectory+currentProcessId.ToString());
> > > ```
> > 
> > 
> > 另外我问一下。 如果程序意外挂了，导致注销代码AutoRegister.UnRegister()没有运行，那当前这个WorkId是不是就以后再也获取不到了？ 长时间后，程序意外挂掉次数累积多了，会不会有WorkId耗尽的风险？
> 
> 1.程序挂了，再启动会尝试获取上一次的workid，但因为你没有唯一标识所以获取不到，基本上可以理解每次都是新的 2.不会，默认WorkId生命周期是30秒,可以手动调整,只有程序没挂会不断续期
> 
> ```cs
> .SetRegisterOption(option => option.WorkerIdLifeMillisecond = 100)
> ```

试过了，确实有效。非常感谢。
