### ISSUE TITLE
SqlServer疑似还是会出现重复的workid

### ISSUE THREAD

**Issue by MayGodBlessYouAMen** [LemonNoCry/SnowflakeId.AutoRegister#2]
源码我加了部分调试日志

1.下面是设置WorkerIdLifeMillisecond=1000的情况，获取到的WorkId都是5，数据库里会有两条Value都是5的数：

![image](https://github.com/user-attachments/assets/1cfd4269-7085-4c35-ad83-6611f8fc8a69)

![image](https://github.com/user-attachments/assets/e603f075-2abe-4fbd-8aa3-6e87f6e0a54e)

2.下面是按照前几天的建议设置WorkerIdLifeMillisecond=100的情况，也会出现重复，而且会伴随一部分Storage.ExpireAsync函数设置失败。
![image](https://github.com/user-attachments/assets/4eedf45b-51a1-4c72-98d7-3d23ae37e464)

![image](https://github.com/user-attachments/assets/5522f207-7622-4f61-8365-60b99805261a)

3.我的问题：

3.1 
  Storage.Set、Storage.Expire方法的SqlServer实现中，where条件目前只用key做条件可能不够，同时还要判断value是否存在，这样能防止value重复的问题。 

3.2
  DefaultAutoRegister类中中，所有的Storage.Expire、Storage.Set等方法可能需要判断返回值，如果是false应该要对应处理。举例：
          
         Storage.Expire(key, RegisterOption.WorkerIdLifeMillisecond);
         Storage.Expire(Identifier, RegisterOption.WorkerIdLifeMillisecond);
         return usedWorkerId;          

          Storage.Set(Identifier, workerId.ToString(), RegisterOption.WorkerIdLifeMillisecond);
          return workerId;

  
3.3
  设置WorkerIdLifeMillisecond=100ms可能不太适合，目前有4台服务器，服务器时间会有细微差别。我设置改成默认的30s好像还好点？

3.4 
一旦两个不同的进程通过GetValidWorkerId()获取到相同的WorkId，后面好像没有救了。
可以考虑加个逻辑：当给workid续期时，发现workid相同的key，但是value不是当前进程的Identifier时，给当前进程重新获取一个新的workid并注册。 
   复现操作：vs启动程序，获取到workid=2，ExtendLifeTimeOperation方法里打个断点中断运行。
                     等待1分钟后，通过exe启动编译好的程序，同样获取到workid=2。这时候取消vs断点，程序继续运行，但是workid也是2
                     这时key=WorkerId:2的value就会在两个Identifier之间不停切换。。。

![image](https://github.com/user-attachments/assets/1dde3c8e-13ee-4c50-b5f5-84c506384478)

![image](https://github.com/user-attachments/assets/e39fbf7b-3c2f-48ca-87e4-21a860c0f66f)

**Comment by MayGodBlessYouAMen** [comment]
目前是生成环境（4台服务器，IIS都开启了多个工作进程）value中出现了重复值，所以我今天做了些测试。应该是有个进程WorkId=4重复了，但是原因未知(ProcessId我添加加过了)。

![image](https://github.com/user-attachments/assets/b3dbd160-421e-4380-a14a-1ead5bfb943d)

**Comment by LemonNoCry** [comment]
我看看

**Comment by LemonNoCry** [comment]
根据你的描述
猜测可能:看起来像是在某个时间点,WorkId过期了,但是标识还没过期,导致另一个进程获取到同个WorkId了,原来进程通过标识还可以继续使用，故此导致争夺了

不存在并发问题,多进程同时拿到WorkId,因为利用数据库insert返回判断,如果workid被其他进程抢先会继续获取其他

核心问题就在:尝试获取之前的WorkId存在问题,如果已经抢先一步被其他进程拿了就会导致，多进程持有相同WorkId

回答你的问题
3.1、3.2：Set目前只用在记录标识、Expire方法只是尝试延期,调整并不能可以解决,因为后台延期线程，假如当前WorkId真的被用了，他也没办法也不能强制结束当前进程，故此只能悲观处理
3.3：不建议设置太小，可能都来不及续期导致被清理掉
3.4: 可以考虑，但是目前还没有一个比较好的方式，例如雪花Id生成都是单例，程序运行就构造好了

**Comment by LemonNoCry** [comment]
先用默认30s试试

设置太短可能导致根本来不及续期

**Comment by LemonNoCry** [comment]
你说的复现方式确实可以复现问题

核心问题就是,你中断了续期线程就可以理解为进程挂了或者“假死状态”,所以其他进程来拿的话就可以拿到，他不知道你还活着

这个确实是个问题,例如网络等等问题产生的"假死状态",生命周期设置长一些能缓解

**Comment by MayGodBlessYouAMen** [comment]
如果是【WorkId过期了,但是标识还没过期】的话，可以考虑把这两个缓存过期时间设置成一模一样的值。
时间太短了确实来不及续期，ClearExpiredValues()方法会把数据清掉，所以总是能写进去(我用100ms测试的情况)。

那我还是先设置30s，观察一段时间再看。

3.4的情况。应该可以通过获取一个新的workid，然后把静态变量idGenInstance实例替换掉解决吧。比如类库里获取Workid冲突时定义一个委托调用，外面IdGeneratorUtil类里实现委托的具体的方法重新new一个idGenInstance。

**Comment by LemonNoCry** [comment]
标识和WorkId的过期时间错开没有关系的,因为获取上一次的WorkId时还会校验WorkId是否被其他进程持有的

3.4 后续设计一下,作为“假死状态”的应对手段

**Comment by LemonNoCry** [comment]
新版已经优化了，看高级用法
