### ISSUE TITLE
Redis连接超时后，导致缓存过期时间未续期？

### ISSUE THREAD

**Issue by zhangkeyuan** [LemonNoCry/SnowflakeId.AutoRegister#3]
使用中遇到一次服务器网络故障，导致redis挂了几分钟，服务A本来获取的机器码是1，但是redis挂了(redis服务几分钟后恢复正常)，导致服务A的机器码缓存未续期，然后服务B重启后获取到机器码也是1了；但是服务A没有重启，导致服务A一直还在使用机器码1，服务B也在使用机器码1。最后生成出重复的雪花Id了

**Comment by LemonNoCry** [comment]
类似于这个问题(https://github.com/LemonNoCry/SnowflakeId.AutoRegister/issues/2#issuecomment-2516606848)

"假死问题":会增加重新注册的逻辑

**Comment by LemonNoCry** [comment]
新版已经优化了，看高级用法

**Comment by MayGodBlessYouAMen** [comment]
非常感谢
